// Carpentry.Angular/ClientApp/src/app/common/visual-card/visual-card.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { DeckCardOverview } from "src/app/decks/models";


@Component({
    selector: 'app-visual-card',
    templateUrl: 'visual-card.component.html',
    styleUrls: ['visual-card.component.less']
})
export class VisualCardComponent implements OnInit {
    @Input() cardOverview: DeckCardOverview;

    @Output() onCardSelected = new EventEmitter<void>();
    
    // children?: ReactNode;

    constructor() {}

    ngOnInit(): void {}
}


<mat-card 
    key={props.cardOverview.name} 
    className={outlineSection}
    onClick={props.onCardSelected}
    >
    <mat-card-header titleTypographyProps="variant:body1" title={ `${props.cardOverview.name} - (${props.cardOverview.count})` } >
        <mat-card-title>
            <!-- toto - ensure spaces appear around the rendered '-' -->
            {{cardOverview.name}} - {{cardOverview.count}}
        </mat-card-title>

    </mat-card-header>

    <img mat-card-image src="cardOverview.img" alt="cardOverview.name" style="height:310px; width: 223px" />

    <!-- <CardMedia 
        style="height:310px; width: 223px"
        image="props.cardOverview.img"
        title="props.cardOverview.name" /> -->
    <!-- {props.children} -->

</mat-card>

// Carpentry.UI/ClientApp/src/_components/VisualCard.tsx
//table of deck cards
import React, { ReactNode } from 'react';

import { CardHeader, CardMedia, Card } from '@material-ui/core';
import { appStyles } from '../styles/appStyles';

interface ComponentProps{
    cardOverview: DeckCardOverview;
    //onCardSelected: ((card: InventoryOverviewDto) => void) | undefined;
    onCardSelected?: () => void;
    children?: ReactNode;
}

export default function VisualCard(props: ComponentProps): JSX.Element {
    const { outlineSection, } = appStyles();
    return (
        <React.Fragment>
            <Card 
                key={props.cardOverview.name} 
                className={outlineSection}
                onClick={props.onCardSelected}
                >
                <CardHeader titleTypographyProps={{variant:"body1"}} title={ `${props.cardOverview.name} - (${props.cardOverview.count})` } />
                {/* <CardHeader titleTypographyProps={{variant:"body1"}} title={`${card.name} (${card.count})`}/> */}
                <CardMedia 
                    style={{height:"310px", width: "223px"}}
                    // className={itemImage}
                    image={props.cardOverview.img}
                    title={props.cardOverview.name} />
                {props.children}

            </Card>

        </React.Fragment>
    );
}
