// Carpentry.Angular/ClientApp/src/app/inventory/inventory-overview/inventory-card-grid/inventory-card-grid.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { InventoryOverviewDto } from "../../models";

@Component({
    selector: 'app-inventory-card-grid',
    templateUrl: 'inventory-card-grid.component.html',
    styleUrls: ['inventory-card-grid.component.less']
})
export class InventoryCardGridComponent implements OnInit{
    // @Input() cardOverviewsById: { [key: number]: InventoryOverviewDto }
    // @Input() cardOverviewIds: number[];
    @Input() cardOverviews: InventoryOverviewDto[];
    
    @Output() onCardSelected = new EventEmitter<number>(); //: (cardId: number) => void;
    @Output() onInfoButtonEnter = new EventEmitter<void>(); //: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
    @Output() onInfoButtonLeave = new EventEmitter<void>(); //: () => void;

    constructor() {}

    ngOnInit(): void {}

    cardSelected(cardId: number): void {
        this.onCardSelected.emit(cardId);
    }
}
<div fxLayout="row wrap" class="flex-row-wrap">                
    <mat-card class="outlineSection" *ngFor="let cardItem of cardOverviews">
        <!-- <CardMedia 
            style="height: 310px; width: 223px"
            image="cardItem.imageUrl"
            title="cardItem.name" /> -->
        <img mat-card-image [src]="cardItem.imageUrl" [alt]="cardItem.name" style="height: 310px; width: 223px;" />
        <div fxLayout="row">
            <mat-card-content>
                <div fxLayout="column">
         
                    <span *ngIf="cardItem.totalCount">
                        no cards
                    </span>
                
                    <span *ngIf="cardItem.inventoryCount">
                        Inventory: {{cardItem.inventoryCount}}
                    </span>
                    
                    <span *ngIf="cardItem.deckCount">
                        Decks: {{cardItem.deckCount}}
                    </span>
                
                    <span *ngIf="cardItem.sellCount">
                        Sell: {{cardItem.sellCount}}
                    </span>
                
                    <span *ngIf="cardItem.totalCount">
                        Total: {{cardItem.totalCount}}
                    </span>
                
                    <span *ngIf="cardItem.isFoil">(FOIL)</span>
                    
                    <span>{{cardItem.price}}</span>
                </div>
            </mat-card-content>
            <mat-card-actions class="flexSection">
                    <button mat-button color="primary" size="small" (click)="cardSelected(cardItem.cardId)">
                        Details
                    </button>
                    <!-- <IconButton 
                        value={cardItem.id} 
                        color="primary" 
                        size="small" 
                        onMouseEnter={props.onInfoButtonEnter}
                        onMouseLeave={props.onInfoButtonLeave}
                        >
                        <InfoOutlined />
                    </IconButton> -->
            </mat-card-actions>
        </div>
    </mat-card>

</div>

// Carpentry/ClientApp/src/inventory/inventory-overview/components/InventoryCardGrid.tsx
import React from 'react';
import { Box, CardContent, Typography, CardMedia, CardActions, Button, Card, IconButton } from '@material-ui/core';
import CardGridContainer from './CardGridContainer';
import { appStyles } from '../../../styles/appStyles';
import { InfoOutlined } from '@material-ui/icons';

interface ComponentProps{
    cardOverviewsById: { [key: number]: InventoryOverviewDto }
    cardOverviewIds: number[];
    onCardSelected: (cardId: number) => void;
    onInfoButtonEnter: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
    onInfoButtonLeave: () => void;
}

export default function InventoryCardGrid(props: ComponentProps): JSX.Element {
    const classes = appStyles();
    return (
        <React.Fragment>
            <CardGridContainer layout="grid">
                { props.cardOverviewIds.map(overviewId => {
                    const cardItem = props.cardOverviewsById[overviewId];
                    return(
                        <Card 
                            title={cardItem.name}
                        key={cardItem.id} 
                        className={classes.outlineSection}>
                            <CardMedia 
                                style={{height:"310px", width: "223px"}}
                                //image={`https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=${props.card.}&type=card`}
                                image={cardItem.imageUrl}
                                title={cardItem.name} />
                            <Box className={classes.flexRow}>
                                <CardContent className={classes.flexSection}>
                                    <Box className={classes.flexCol}>
                                        { cardItem.totalCount === 0 &&
                                            <Typography>
                                                no cards
                                            </Typography>
                                        }
                                        { Boolean(cardItem.inventoryCount) &&
                                            <Typography>
                                                {`Inventory: ${cardItem.inventoryCount}`}
                                            </Typography>
                                        }
                                        { Boolean(cardItem.deckCount) &&
                                            <Typography>
                                                {`Decks: ${cardItem.deckCount}`}
                                            </Typography>
                                        }
                                        { Boolean(cardItem.sellCount) &&
                                            <Typography>
                                                {`Sell: ${cardItem.sellCount}`}
                                            </Typography>
                                        }
                                        { Boolean(cardItem.totalCount) &&
                                            <Typography>
                                                {`Total: ${cardItem.totalCount}`}
                                            </Typography>
                                        }
                                        { cardItem.isFoil && <Typography>(FOIL)</Typography> }
                                        {/* <Typography>
                                            ${ cardItem.isFoil ? cardItem.priceFoil : cardItem.price }
                                        </Typography> */}
                                        <Typography>${cardItem.price}</Typography>
                                    </Box>
                                </CardContent>
                                <CardActions className={classes.flexSection}>
                                        <Button color="primary" size="small" onClick={() => {props.onCardSelected(cardItem.cardId)}} >
                                            Details
                                        </Button>
                                        <IconButton 
                                            value={cardItem.id} 
                                            color="primary" 
                                            size="small" 
                                            onMouseEnter={props.onInfoButtonEnter}
                                            onMouseLeave={props.onInfoButtonLeave}
                                            >
                                            <InfoOutlined />
                                        </IconButton>
                                </CardActions>
                            </Box>
                        </Card>
                    )} 
                )}
            
            </CardGridContainer>
        </React.Fragment>
    );
}
