// Carpentry/ClientApp/src/decks/deck-editor/components/DeckCardDetail.tsx
import {  Table, TableHead, TableRow, TableCell, TableBody, Box, CardActions, Button, Card, CardHeader, CardMedia, CardContent, Typography, IconButton } from '@material-ui/core';
import React from 'react';
import { MoreVert } from '@material-ui/icons';
import { appStyles } from '../../../styles/appStyles';

interface ComponentProps{
    //totalPrice: number;
    // deckProperties: DeckProperties;
    // onEditClick: () => void;
    // cardOverviews: InventoryOverviewDto[];
    // onCardSelected: (card: InventoryOverviewDto) => void;
    selectedCard: DeckCardOverview | null;

    inventoryCards: DeckCardDetail[];

    onMenuClick: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
    onMenuClose: () => void;
    onCardDetailClick: (cardId: number) => void;
    // onMenuSelect: (option: string) => void;
}

export default function DeckCardDetail(props: ComponentProps): JSX.Element {
    const { staticSection } = appStyles();
    if(props.selectedCard === null){
        return (
            <Box className={staticSection}>
                <Card>
                    <CardHeader titleTypographyProps={{variant:"body1"}} title={"no card selected"}/>
                    <CardContent>
                        <Typography>select a card</Typography>
                    </CardContent>
                </Card>
            </Box>
        );
    }
    else {
        return (
            <Box className={staticSection}>
                
                <Card>
                    {/* <CardHeader 
                        titleTypographyProps={{variant:"body1"}} 
                        title={props.selectedCard.name}
                        // action={
                        //     <Button 
                        //         onClick={() => { }} 
                        //         color="primary" 
                        //         variant="contained"
                        //         >Find More</Button>
                        // }
                    
                    /> */}
                    {
                        props.selectedCard && 
                        <CardMedia style={{height:"310px", width: "223px"}} image={props.selectedCard.img} />
                    }
                    <CardContent>
                        <Table size="small">
                            <TableHead>
                                <TableRow>
                                    <TableCell>Card Detail</TableCell>
                                    <TableCell></TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                            {
                                props.inventoryCards.map(item => {

                                    const rowDeckCardId = item.id;
                                    return(
                                    <TableRow key={item.id}>
                                        {
                                            item.inventoryCardId && 
                                            <TableCell style={{textTransform:"uppercase"}}>
                                                {`${item.set} - ${item.collectorNumber}`}{item.isFoil &&" (foil)"}
                                            </TableCell>
                                        }
                                        {
                                            !item.inventoryCardId &&
                                            <TableCell>
                                                Empty
                                            </TableCell>
                                        }
                                        <TableCell size="small">
                                            {/* <IconButton size="small" onClick={props.onMenuClick} name={item.name} value={item.multiverseId}> */}
                                            {/* item.deckCards[0].id */}
                                            <IconButton size="small" onClick={props.onMenuClick} name={item.name} value={rowDeckCardId}>
                                                <MoreVert />
                                            </IconButton>
                                        </TableCell>
                                    </TableRow>
                                    )
                                })
                            }
                            </TableBody>
                        </Table>
                    </CardContent>
                    <CardActions>
                        <Button 
                            onClick={() => props.selectedCard && props.onCardDetailClick(props.selectedCard.cardId)} 
                            color="primary" 
                            variant="contained"
                            >Card Details</Button>
                    </CardActions>
                </Card>
            </Box>
        );
    }
}

// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-card-detail/deck-card-detail.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { DeckCardDetail, DeckCardOverview } from "../../models";

@Component({
    selector: 'app-deck-card-detail',
    templateUrl: 'deck-card-detail.component.html',
    styleUrls: ['deck-card-detail.component.less']
    
})
export class DeckCardDetailComponent implements OnInit {
    @Input() selectedCard: DeckCardOverview | null;
    @Input() inventoryCards: DeckCardDetail[];

    @Output() onMenuClick = new EventEmitter<void>();
    // (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;

    @Output() onMenuClose = new EventEmitter<void>();
    @Output() onCardDetailClick = new EventEmitter<number>();
    @Output() onCardTagsClick = new EventEmitter<number>();

    
    constructor() {}

    ngOnInit(): void {}

    menuClick(): void {
        this.onMenuClick.emit();
    }

    menuClose(): void {
        this.onMenuClose.emit();
    }

    cardDetailClick(): void {
        this.onCardDetailClick.emit();
    }

    cardTagsClick(): void {
        this.onCardTagsClick.emit();
    }
}
<!-- (props.selectedCard === null) -->
<div className="staticSection">
    <mat-card>
        <mat-card-header>
            <!-- TODO - figure out to how to render as a body1 instead of [whatever the title is] -->
            <mat-card-title>
                <p>no card selected</p>
            </mat-card-title>
        </mat-card-header>
        <mat-card-content>
            <p>select a card</p>
        </mat-card-content>
    </mat-card>
</div>

<!-- else -->
<div className="staticSection">
                
    <mat-card>
        <img *ngIf="selectedCard" style="height:310px; width: 223px" src="selectedCard.img" />

        <mat-card-content>
            <table size="small">
                <tr>
                    <th>Card Detail</th>
                    <th></th>
                </tr>
            
                <tr *ngFor="let item of inventoryCards">

                    <td *ngIf="item.inventoryCardId" style="text-transform:uppercase">
                        {{item.set}} - {{item.collectorNumber}}{{item.isFoil && "(foil)"}}
                    </td>
                    <td *ngIf="!item.inventoryCardId">
                        Empty
                    </td>
                    
                    <td size="small">
                        <a mat-icon-button (click)="menuClick()">more_vert</a>
                        <!-- <IconButton size="small" onClick={props.onMenuClick} name={item.name} value="item.id">
                            <MoreVert />
                        </IconButton> -->
                    </td>
                </tr>
            </table>
        </mat-card-content>
        <mat-card-actions>
            <button mat-button (click)="selectedCard && cardDetailClick(selectedCard.cardId)"
                color="primary" variant="contained">Details</button>
            <button mat-button (click)="selectedCard && cardTagsClick(selectedCard.cardId)"
                color="primary" variant="contained">Tags</button>
        </mat-card-actions>
    </mat-card>
</div>
