// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/grouped-deck-card-list/grouped-deck-card-list.component.ts


import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { CardOverviewGroup, DeckCardDetail, DeckCardOverview } from "../../models";

@Component({
    selector: 'app-grouped-deck-card-list',
    templateUrl: 'grouped-deck-card-list.component.html',
    styleUrls: ['grouped-deck-card-list.component.less'],
})
export class GroupedDeckCardListComponent implements OnInit {
    @Input() groupedCardOverviews: CardOverviewGroup[];
    @Input() cardDetailsById: { [deckCardId: number]: DeckCardDetail };
    
    @Output() onCardSelected = new EventEmitter<DeckCardOverview>()    
    @Output() onCardDetailClick = new EventEmitter<number>();
    @Output() onCardTagsClick = new EventEmitter<number>();

    constructor() {}
    ngOnInit(): void {}

    cardSelected(overview: DeckCardOverview): void {
        this.onCardSelected.emit(overview);
    }

    cardDetailClick(id: number): void {
        this.onCardDetailClick.emit(id);
    }

    cardTagsClick(id: number): void {
        this.onCardTagsClick.emit(id);
    }
}
<mat-card>
    <!-- TODO - replace with material table -->

    <table size="small">
        <!-- Need to research better ways to handle this style table, it might work even better as a mat table -->
        <!-- I'm adding a DIV but that really may break things, I don't know what the Angular equivalent to a React.Fragment is -->
        <div class="react-fragment" *ngFor="let group of groupedCardOverviews">
            <tr>
                <th size="medium"></th>
                <th size="medium" colspan="4">{{group.name}} ({{group.cardOverviews.length}})</th>
            </tr>

            <tr *ngFor="let cardItem of group.cardOverviews"
                (click)="cardSelected(cardItem)" (mouseenter)="cardSelected(cardItem)">
                
                <td>{{cardItem.count}}</td>
                <td>{{cardItem.name}}</td>
                <td>
                    <button mat-button *ngIf="cardItem.tags.length" variant="outlined" style="text-transform:none" (click)="cardTagsClick(cardItem.cardId)">
                        {{cardItem.tags.toString()}}
                    </button>                                                    
                    
                    <button mat-button *ngIf="!cardItem.tags.length" style="text-transform:none" (click)="cardTagsClick(cardItem.cardId)">
                        untagged
                    </button>
                </td>
                <td>
                    <!-- <ManaCostChip costString={cardItem.cost} /> -->
                </td>
                <td>
                <button color="inherit" (click)="cardDetailClick(cardItem.cardId)">

                    <!-- {
                        cardItem.detailIds.map(id => {
                            const cardDetail = props.cardDetailsById[id];
                            let color = GetAvailabilityColor(cardDetail.availabilityId);
                            return(<Star style={{color: color}} key={id} />);
                        })
                    } -->
                </button>
                </td>
                
            </tr>
    
        </div>
    
    </table>
</mat-card>

// Carpentry.React/ClientApp/src/features/decks/deck-editor/components/GroupedDeckCardList.tsx
import React from 'react'
import { Paper, Table, TableHead, TableRow, TableCell, TableBody, IconButton, Button } from '@material-ui/core';
import { Star } from '@material-ui/icons';
import ManaCostChip from "../../../../common/components/ManaCostChip";
// import {push} from "react-router-redux";

interface ComponentProps{
  groupedCardOverviews: CardOverviewGroup[];
  cardDetailsById: { [deckCardId: number]: DeckCardDetail };
}

export default function GroupedDeckCardList(props: ComponentProps): JSX.Element {
  function GetAvailabilityColor(availabilityId: number): string {
    switch(availabilityId){
      case 1: return "green";
      case 2: return "yellow";
      case 3: return "orange";
      case 4: return "red";
      default: return "blue";
    }
  }

  const onCardSelected = (card: DeckCardOverview): void => {
    //dispatch(deckEditorCardSelected(cardOverview))
  }

  const onCardDetailClick = (cardId: number): void => {
    //dispatch(push(`/decks/${this.props.deckId}?cardId=${cardId}&show=detail`));
  }

  const onCardTagsClick = (cardId: number): void => {
    // dispatch(push(`/decks/${this.props.deckId}?cardId=${cardId}&show=tags`));
  }

  return (
    <Paper>
      <Table size="small">
        {
          props.groupedCardOverviews.map(group => (
            <React.Fragment key={group.name}>
              <TableHead key={`th-${group.name}`}>
                <TableRow>
                  <TableCell size="medium"/>
                  <TableCell size="medium" colSpan={4}>{group.name} ({group.cardOverviews.length})</TableCell>
                </TableRow>
              </TableHead>
              <TableBody key={`tb-${group.name}`}>
                {
                  group.cardOverviews.map(cardItem =>
                    <TableRow onClick={() => onCardSelected(cardItem)} onMouseEnter={() => onCardSelected(cardItem)}
                              key={cardItem.id+cardItem.name}>
                      <TableCell>{cardItem.count}</TableCell>
                      <TableCell>{cardItem.name}</TableCell>
                      <TableCell>
                        {
                          Boolean(cardItem.tags.length) ?
                            <Button variant="outlined" style={{textTransform:"none"}} onClick={()=>{onCardTagsClick(cardItem.cardId)}} >
                              {cardItem.tags.toString()}
                            </Button>
                            :
                            <Button style={{textTransform:"none"}} onClick={()=>{onCardTagsClick(cardItem.cardId)}}>
                              untagged
                            </Button>
                        }
                      </TableCell>
                      <TableCell><ManaCostChip costString={cardItem.cost} /></TableCell>
                      <TableCell>
                        <Button color="inherit" onClick={()=>{onCardDetailClick(cardItem.cardId)}} >
                          {
                            cardItem.detailIds.map(id => {
                              const cardDetail = props.cardDetailsById[id];
                              let color = GetAvailabilityColor(cardDetail.availabilityId);
                              return(<Star style={{color: color}} key={id} />);
                            })
                          }
                        </Button>
                      </TableCell>
                    </TableRow>
                  )
                }
              </TableBody>
            </React.Fragment>
          ))
        }
      </Table>
    </Paper>
  );
}
