// UIAngularTest/ClientApp/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { convertToObject } from 'typescript';
import { AppConfigService } from '../app-config.service';
import { AppConfigResult } from '../models';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.less'],
})
export class HomeComponent implements OnInit {
  isLoading: boolean;
  appConfigStatus: 'Not Loaded'|'Loading...'|'Loaded'; //string;

  appConfig: AppConfigResult;

  constructor(
    private appStatusService: AppConfigService,
  ) { }

  ngOnInit(): void {
    this.appConfig = null;
    this.appConfigStatus = "Not Loaded"
  }

  onRefreshClick(): void {
    this.getAppStatus();
  }

  private getAppStatus(): void {
    this.isLoading = true;
    this.appConfigStatus = "Loading..."
    this.appStatusService.getAppConfig().subscribe(result => {
      this.appConfig = result;
      this.appConfigStatus = "Loaded"
      this.isLoading = false;
    });
  }
}

<div>
  <h1>Hello, world!</h1>
  <p>This is a simple example app written with Angular!</p>
</div>
<div>
  <h4>App Config: <span id="app-config-status">{{appConfigStatus}}</span></h4>
  <h4 *ngIf="!isLoading && appConfig">Configured Value: <span id="config-string">{{appConfig.configString}}</span></h4>
  <h4 *ngIf="!isLoading && appConfig">Last Updated: <span id="config-last-updated">{{appConfig.lastUpdated | date:'short'}}</span></h4>
  <button id="refresh-button" (click)="onRefreshClick()" [disabled]="isLoading">Refresh</button>
</div>

// UIReactTest/ClientApp/src/components/Home.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router';
import { actionCreators, AppReducerState } from '../state/AppReducer';
import { ApplicationState } from '../store';

type HomeProps = AppReducerState & typeof actionCreators;

class Home extends React.PureComponent<HomeProps> {
  public render() {
    return (
      <React.Fragment>
        <div>
          <h1>Hello, world!</h1>
          <p>This is a simple example app written with React and Redux!</p>
        </div>
        <div>
          <h4>App Config: <span id="app-config-status">{this.props.appConfigStatus}</span></h4>
          { !this.props.isLoading && this.props.appConfig &&
            <h4>Configured Value: <span id="config-string">{this.props.appConfig.configString}</span></h4>
          }
          {
            !this.props.isLoading && this.props.appConfig &&
            <h4>Last Updated: <span id="config-last-updated">{this.props.appConfig.lastUpdated}</span></h4>
          }
          <button id="refresh-button" onClick={() => { this.getAppConfig() }} disabled={this.props.isLoading}>
            Refresh
          </button>
        </div>
      </React.Fragment>
    );
  }

  private getAppConfig() {
    this.props.getAppConfig();
  }
}

export default connect(
  (state: ApplicationState) => state.appConfig,
  actionCreators
)(Home as any);
