// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-props-bar/deck-props-bar.component.ts
import { Component, OnInit } from "@angular/core";
import { DeckPropertiesDto } from "../../models";

@Component({
    selector: 'app-deck-props-bar',
    templateUrl: 'deck-props-bar.component.html',
    styleUrls: ['deck-props-bar.component.less']
})
export class DeckPropsBarComponent implements OnInit {
    deckProperties: DeckPropertiesDto;
    
    constructor() {
        this.deckProperties = {
            id: 0,
            name: "loading...",
            notes: '',
            format: '',
            basicB: 0,
            basicG: 0,
            basicR: 0,
            basicU: 0,
            basicW: 0,
        }
    }

    ngOnInit(): void {
        
    }

    onToggleViewClick(): void {

    }

    onEditClick(): void {

    }

    onExportClick(): void {

    }

    onAddCardsClick(): void {

    }
}
<div>
    <mat-toolbar color="default" position="relative">

        <h5 >Deck Editor </h5>
        &nbsp;
        <h5> {{deckProperties.name}} </h5>

            <div>
                <mat-chip-list>

                
                <mat-chip *ngIf="deckProperties.basicW">
                    <img width="20" height="20" src='/assets/W.svg' />
                    {{deckProperties.basicW}}
                </mat-chip>

                <mat-chip *ngIf="deckProperties.basicU">
                    <img width="20" height="20" src='/assets/U.svg' />
                    {{deckProperties.basicU}}
                </mat-chip>

                <mat-chip *ngIf="deckProperties.basicB">
                    <img width="20" height="20" src='/assets/B.svg' />
                    {{deckProperties.basicB}}
                </mat-chip>

                <mat-chip *ngIf="deckProperties.basicR">
                    <img width="20" height="20" src='/assets/R.svg' />
                    {{deckProperties.basicR}}
                </mat-chip>

                <mat-chip *ngIf="deckProperties.basicG">
                    <img width="20" height="20" src='/assets/G.svg' />
                    {{deckProperties.basicG}}
                </mat-chip>

            </mat-chip-list>
                <!-- <mat-chip-list>
                    <mat-chip  avatar=>

                    </mat-chip>
                </mat-chip-list> -->
                

                <!-- <Chip size="small" avatar={<Avatar src={'/img/W.svg'}/>} label={ basicW }/> -->
                <!-- <Chip size="small" avatar={<Avatar src={'/img/U.svg'}/>} label={ basicU }/> -->
                <!-- <Chip size="small" avatar={<Avatar src={'/img/B.svg'}/>} label={ basicB }/> -->
                <!-- <Chip size="small" avatar={<Avatar src={'/img/R.svg'}/>} label={ basicR }/> -->
                <!-- <Chip size="small" avatar={<Avatar src={'/img/G.svg'}/>} label={ basicG }/> -->

<!-- 
const ManaChip = (type: String, value: number): JSX.Element => 
(<Chip size="small" avatar={<Avatar src={`/img/${type}.svg`}/>} label={ value }/>); -->

            </div>
            <div>
                <button mat-button (click)="onToggleViewClick()" color="primary" variant="contained">
                    Toggle View
                </button>
                <button mat-button (click)="onEditClick()" color="primary" variant="contained">
                    Edit
                </button>
                <button mat-button (click)="onExportClick()" color="primary" variant="contained">
                    Export
                </button>
                <button mat-button (click)="onAddCardsClick()" color="primary" variant="contained">
                    Add Cards
                </button>
            </div>
        
     
    </mat-toolbar>
</div>
<!-- 
<header>
    <mat-toolbar color="primary" class="mat-elevation-z6">
      <div class="container">
        <a class="navbar-brand" [routerLink]="['/']">Carpentry</a>
        <a mat-button [routerLink]="['/decks']">Decks</a>
        <a mat-button [routerLink]="['/inventory']">Inventory</a>
        <a mat-button [routerLink]="['/settings']">Settings</a>
      </div>
    </mat-toolbar>
  </header>
  
   -->

// Carpentry.UI/ClientApp/src/containers/DeckEditor/DeckPropsBar.tsx
import React from 'react';

import { Typography, Box, AppBar, Chip, Toolbar, Avatar, Button } from '@material-ui/core';
import { Link } from 'react-router-dom';

interface ComponentProps{
    //totalPrice: number;
    deckProperties: DeckPropertiesDto;
    onEditClick: () => void;
    onToggleViewClick: () => void;
    // onAddCardsClick: () => void;
}

const ManaChip = (type: String, value: number): JSX.Element => 
    (<Chip size="small" avatar={<Avatar src={`/img/${type}.svg`}/>} label={ value }/>);

export default function DeckPropsBar(props: ComponentProps): JSX.Element {

    const { basicW, basicU, basicB, basicR, basicG } = props.deckProperties;

    return (
        <AppBar color="default" position="relative">
            <Toolbar>
                {/* <Typography variant="h5">Deck Editor</Typography> */}
                <Typography variant="h5">{props.deckProperties.name}</Typography>
                {/* &nbsp; */}
                {/* <Typography variant="h6">--{props.deckProperties && props.deckProperties.name+ ' - '+ props.deckProperties.notes}</Typography> */}
                <Box>
                {/* <div className= "flex-section flex-25"> */}
                    { basicW > 0 && ManaChip('W',basicW)}
                    { basicU > 0 && ManaChip('U',basicU)}
                    { basicB > 0 && ManaChip('B',basicB)}
                    { basicR > 0 && ManaChip('R',basicR)}
                    { basicG > 0 && ManaChip('G',basicG)}
                    {/* <Chip size="small" avatar={<Avatar src="/img/W.svg" />} label={ basicW }/> */}
                    
                    
                    {/* <Chip size="small" avatar={<Avatar src="/img/W.svg" />} label={ basicW }/> */}
                    {/* <Chip size="small" avatar={<Avatar src="/img/U.svg" />} label={ basicU }/>
                    <Chip size="small" avatar={<Avatar src="/img/B.svg" />} label={ basicB }/>
                    <Chip size="small" avatar={<Avatar src="/img/R.svg" />} label={ basicR }/>
                    <Chip size="small" avatar={<Avatar src="/img/G.svg" />} label={ basicG }/> */}
                </Box>
                <Box>
                    <Button onClick={props.onToggleViewClick} color="primary" variant="contained">
                        Toggle View
                    </Button>
                    <Button onClick={props.onEditClick} color="primary" variant="contained">
                        Edit
                    </Button>
                    {/* <Button onClick={props.onAddCardsClick} color="primary" variant="contained">
                        Add Cards
                    </Button> */}
                    <Link to={`/decks/${props.deckProperties.id}/addCards/`}>
                        <Button color="primary" variant="contained">Add Cards</Button>
                    </Link>
                </Box>
            </Toolbar>
        </AppBar>
    );
}
