// Carpentry/ClientApp/src/features/inventory/inventory-detail/InventoryDetail.tsx
﻿import {
  Box,
  Button,
  Card,
  CardHeader,
  CardMedia,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle, Table, TableBody, TableCell, TableHead, TableRow, Typography
} from "@material-ui/core";
import React, {useEffect} from "react";
import styles from "../../../App.module.css";
import {useHistory} from "react-router";
import {useAppDispatch, useAppSelector} from "../../../hooks";
import {combineStyles} from "../../../styles/appStyles";
import {ApiStatus} from "../../../enums";
import {loadInventoryDetail} from "./InventoryDetailSlice";

interface OwnProps {
  match: {
    params: {
      cardId: string;
    }
  }
}

const InventoryDetailCard = (props: { cardId: number }): JSX.Element => {
  const card = useAppSelector(state => state.inventory.detail.data.cardsById[props.cardId]);
  const inventoryCardIds = useAppSelector(state => state.inventory.detail.data.cardGroups[props.cardId]);
  const img = card.imageUrl;
  const cardTitle = `${card.set} (${card.collectionNumber}) - $${card.price} | $${card.priceFoil}`;

  // TODO - Inventory Card Rows should probably be their own component
  const inventoryCardsById = useAppSelector(state => state.inventory.detail.data.inventoryCardsById);

  return (
    <Card key={card.cardId} className={combineStyles(styles.outlineSection, styles.flexCol)}>
      <CardHeader titleTypographyProps={{variant:"body1"}} style={{textTransform:"uppercase"}} title={cardTitle} />
      <Box className={combineStyles(styles.flexRow, styles.flexSection)}>
        <Box className={styles.staticSection}>
          <CardMedia style={{height:"310px", width: "223px"}} image={img} />
        </Box>

        <Box className={combineStyles(styles.flexSection, styles.flexCol)}>
          <Box className={styles.scrollSection} style={{overflow:"auto"}}>
            <Table size="small" >
              <TableHead>
                <TableRow>
                  <TableCell>Style</TableCell>
                  <TableCell>Status</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {
                  inventoryCardIds.map(inventoryCardId => {
                    const item = inventoryCardsById[inventoryCardId];
                    return(
                      <TableRow key={item.id}>
                        <TableCell>
                          <Typography>{(item.isFoil && " foil") || "normal"}</Typography>
                        </TableCell>
                        <TableCell>
                          <Typography>
                            { item.statusId === 1 && "Inventory/Deck" }
                            { item.statusId === 2 && "Wish List" }
                            { item.statusId === 3 && "Sell List" }
                          </Typography>
                        </TableCell>
                      </TableRow>
                    )
                  })
                }
              </TableBody>
            </Table>
          </Box>
        </Box>
      </Box>
    </Card>
  )
}

export const InventoryDetail = (props: OwnProps): JSX.Element => {

  const selectedCardId = +props.match.params.cardId;
  
  const modalIsOpen = Boolean(selectedCardId != null);

  const allCardIds = useAppSelector(state => state.inventory.detail.data.allCardIds);
  
  // TODO - This should really be a selector in the slice, or just be smarter...
  const shouldLoad = useAppSelector(state => {

    const apiStatus = state.inventory.detail.data.status
    
    if(apiStatus === ApiStatus.uninitialized) return true;
    
    if(apiStatus === ApiStatus.initialized){
      const idsMatch = state.inventory.detail.selectedCardId === selectedCardId;
      if(!idsMatch) return true;
    }
    return false;
  });
  
  const history = useHistory();
  
  const handleCloseModalClick = (): void => {
    history.push('/inventory');
  }
  
  const dispatch = useAppDispatch();
  
  useEffect(() => {
    if(shouldLoad) dispatch(loadInventoryDetail(selectedCardId));
  });
  
  const cardName = useAppSelector(state => state.inventory.detail.data.selectedCardName);
  
  return (
    <React.Fragment>
      <Dialog open={modalIsOpen} onClose={() => {handleCloseModalClick()}} >
        <DialogTitle>{`Inventory Detail - ${cardName}`}</DialogTitle>
        <DialogContent>
          <Box className={combineStyles(styles.flexCol, styles.flexSection)}>
            {
              allCardIds.map(cardId => <InventoryDetailCard key={cardId} cardId={cardId} />)
            }
          </Box>
        </DialogContent>
        <DialogActions>
          <Button size="medium" onClick={() => handleCloseModalClick()}>Close</Button>
        </DialogActions>
      </Dialog>
    </React.Fragment>
  )
}

// Carpentry.Angular/ClientApp/src/app/inventory/inventory-detail/inventory-detail.component.ts
import { Component, OnInit } from "@angular/core";
import { CardOverviewGroup, DeckCardOverview, DeckDetailDto, DeckPropertiesDto, GroupedCardOverview } from "src/app/decks/models";
import { InventoryCard, MagicCard } from "../models";

@Component({
  selector: 'app-inventory-detail',
  templateUrl: 'inventory-detail.component.html',
  styleUrls: ['inventory-detail.component.less'],
})
export class InventoryDetailComponent implements OnInit {
  
    // @Input() deckId: number;

    // deckDetail: DeckDetailDto;

    // deckId: number;
    // viewMode: 'grid' | 'list' | 'grouped'; // DeckEditorViewMode;
    
    // deckProperties: DeckPropertiesDto | null;

    // // formatFilterOptions: FilterOption[];

    // // deckStats: DeckStats | null;

    // // isPropsDialogOpen: boolean;

    // // deckDialogProperties: DeckPropertiesDto | null;

    // // groupedCardOverviews: CardOverviewGroup[];
    // // cardDetailsById: { [deckCardId: number]: DeckCardDetail };

    // // cardMenuAnchor: HTMLButtonElement | null;
    // // cardMenuAnchorId: number;

    // // selectedCard: DeckCardOverview | null;
    // // selectedInventoryCards: DeckCardDetail[];

    // // selectedCardId: number;
    // // isCardDetailDialogOpen: boolean;
    // // isCardTagsDialogOpen: boolean;

    // // isExportDialogOpen: boolean;
    // // selectedExportType: DeckExportType;

    // // cardOverviews: {
    // //     byId: { [id: number]: DeckCardOverview }
    // //     allIds: number[];
    // // };

    // // cardDetails: {
    // //     byId: { [deckCardId: number]: DeckCardDetail };
    // //     allIds: number[];
    // // };


    // // cardGroups: NamedCardGroup[];
    
    // groupedCardOverviews: CardOverviewGroup[];

    // newGroupingMethod: GroupedCardOverview[];

    
    // // selectedOverviewCardId: number | null;
    // selectedOverview: DeckCardOverview | null;


    // selectedDetailItem: InventoryDetailDto;
    modalIsOpen: boolean;
    selectedCardId: number;

    // selectedCardId: number;
    cardsById: { [cardId: number]: MagicCard }
    allCardIds: number[];
    inventoryCardsById: { [inventoryCardId: number]: InventoryCard }
    cardGroups: { [cardId: number]: number[] }

    cardName: string;

    
    constructor() { }
    ngOnInit(): void {
      // this.dialogTitle = `Inventory Detail - ${cardName}`;
      this.loadInventoryDetail(); //TODO - subscribe and whatnot


      this.setCardName();



    }
    
    private loadInventoryDetail(): void {
      //get card id from dialog props

      //do whatever react does...


      //--------------------------


      //this.props.dispatch(ensureInventoryDetailLoaded(this.props.selectedCardId))
      

      // //Has a load been requested?
      // //  if yes, return
      // //So this could be two variables: queryIsLoaded, loadedId
      // //  OR...wait still 2 variables: queryIsLoading, loadedId
      // //  Okay, so I guess I won't change that approach

      // // if(queryInProgress){
      // //     return;
      // // }
      // const selectedCardId = state.inventory.data.detail.selectedCardId;
      // const queryIsLoading = state.inventory.data.detail.isLoading;

      // if(queryIsLoading || cardId === selectedCardId){
      //     return;
      // }

      // //So, should I dispatch this data action, or add a local action somewhere?
      // dispatch(inventoryDetailRequested(cardId));

      // inventoryApi.getInventoryDetail(cardId).then((result) => {
      //     dispatch(inventoryDetailReceived(result));
      // }).catch((error) => {
      //     dispatch(inventoryDetailReceived(null));
      // });


    }

    //   const inventoryDetailRequested = (state: InventoryDataReducerState, action: ReduxAction): InventoryDataReducerState => {
    //     const selectedCardId = action.payload;
    //     const newState: InventoryDataReducerState = {
    //         ...state,
    //         detail: {
    //             ...initialState.detail,
    //             isLoading: true,
    //             selectedCardId: selectedCardId, //will be number
    //         }
    //     };
    //     return newState;
    // }


    //   const inventoryDetailReceived = (state: InventoryDataReducerState, action: ReduxAction): InventoryDataReducerState => {
    //     const detailResult: InventoryDetailDto | null = action.payload;
    
    //     if(detailResult === null){
    //         return {
    //             ...initialState,
    //         }
    //     }
    
    //     let inventoryCardsById = {}
    //     detailResult.inventoryCards.forEach(invCard => inventoryCardsById[invCard.id] = invCard);
    //     const allInventoryCardIds = detailResult.inventoryCards.map(card => card.id);
    
    //     let cardsById = {}
    //     detailResult.cards.forEach(card => cardsById[card.multiverseId] = card);
    //     const allCardIds = detailResult.cards.map(card => card.multiverseId);
    
    //     //fill card groups
        
    //     let cardGroups: { [cardId: number]: number[] } = {};
    //     // let cardGroupIds: number[];
    //     allCardIds.forEach(cardId => {
    //         const thisCard = cardsById[cardId];
    //         // cardGroupIds.push()
    //         const inventoryCardIds = allInventoryCardIds
    //             .filter(inventoryCardId => inventoryCardsById[inventoryCardId].set === thisCard.set 
    //                 && inventoryCardsById[inventoryCardId].collectorNumber === thisCard.collectionNumber);
    //         cardGroups[cardId] = inventoryCardIds;
    //     });
        
    //     //
    
    
    //     const newState: InventoryDataReducerState = {
    //         ...state,
    //         detail: {
    //             selectedCardId: state.detail.selectedCardId,
    //             selectedCardName: detailResult.name,
    //             isLoading: false,
    
    //             inventoryCardsById: inventoryCardsById,
    //             inventoryCardAllIds: allInventoryCardIds,
                
    //             cardsById: cardsById,
    //             allCardIds: allCardIds,
    
    //             cardGroups: cardGroups,
    //         },
    //     };
    //     return newState;
    // }


  //   function mapStateToProps(state: AppState, ownProps: OwnProps): PropsFromState {
  //     // const containterState = state.
  //     const detailData = state.inventory.data.detail;
  //     const result: PropsFromState = {
  //         // selectedDetailItem: selectInventoryDetail(state),
  //         // modalIsOpen: state.ui.isInventoryDetailModalOpen, //TODO - get this mapped from router state
  //         selectedCardId: ownProps.match.params.cardId,
  //         allCardIds: detailData.allCardIds,
  //         cardsById: detailData.cardsById,
  //         cardGroups: detailData.cardGroups,
  //         inventoryCardsById: detailData.inventoryCardsById,
  //         modalIsOpen: Boolean(ownProps.match.params.cardId != null),
  //     }
  //     return result;
  // }

    private setCardName(){
      this.cardName = "Unknown";

      if(this.allCardIds.length > 0){
        this.cardName = this.cardsById[this.allCardIds[0]].name;
      }
    }
}
<!-- For some reason it bothers me that this file doesn't have to be wrapped in a specific tag -->
<!-- <h4 mat-dialog-title>Deck Properties</h4>
<div mat-dialog-content>
    <div>
        <mat-form-field>
            <mat-label>Name</mat-label>
            <input matInput color="primary" [(ngModel)]="deckProps.name" />
        </mat-form-field>
    </div>
    <div>
        <mat-form-field>
            <mat-label>Format</mat-label>
            <mat-select [(ngModel)]="deckProps.format">
                <mat-option *ngFor="let filter of formatFilterOptions" [value]="filter.name">{{filter.name}}</mat-option>
            </mat-select>
        </mat-form-field>
    </div>
    <div>
        <mat-form-field>
            <mat-label>Notes</mat-label>
            <input matInput color="primary" [(ngModel)]="deckProps.notes" />
        </mat-form-field>
    </div>
    <div fxLayout="row" class="flex-row" *ngIf="deckProps.id > 0">
        <mat-form-field fxFlex="20">
            <input matInput color="primary" type="number" [(ngModel)]="deckProps.basicW" />
            <span matPrefix>W&nbsp;</span>
        </mat-form-field>
    </div>
</div>
<div mat-dialog-actions fxLayout="column" fxLayoutAlign="none end" fxLayoutGap="10px">
    <div>
        <button mat-raised-button color="warn" (click)="onDisassembleClick()">Disassemble</button>
        <button mat-raised-button color="warn" (click)="onDeleteClick()">Delete</button>
    </div>
    <div>
        <button mat-raised-button (click)="onCancelClick()">Cancel</button>
        <button mat-raised-button color="primary" (click)="onSaveClick()">Save</button>
    </div>
</div> -->


<!-- <h4 mat-dialog-title>{`Inventory Detail - ${cardName}`}</h4> -->
<h4 mat-dialog-title>{{cardName}}</h4>
        
<div mat-dialog-content>
<!-- <InventoryDetailLayout
//  selectedDetailItem={this.props.selectedDetailItem}
// selectedCardId={this.props.selectedCardId}
cardGroups={this.props.cardGroups}
cardsById={this.props.cardsById}
allCardIds={this.props.allCardIds}
inventoryCardsById={this.props.inventoryCardsById}
    /> -->
    <!-- <div>HalloModal</div> -->

    <div class="flex-col flex-section">

    <!-- {
        props.allCardIds.map(cardId => {
            let card = props.cardsById[cardId];
            let inventoryCardIds = props.cardGroups[cardId];
            let img = card.imageUrl;
            let cardTitle = `${card.set} (${card.collectionNumber}) - $${card.price} | $${card.priceFoil}`;

            return ( -->
                <!-- <Card key={card.cardId} class={combineStyles(outlineSection, flexCol)}> -->
                    <!-- <CardHeader titleTypographyProps={{variant:"body1"}} style={{textTransform:"uppercase"}} title={cardTitle} /> -->
                    
                    <div class="flex-row flex-section"> 
                        <!-- <div class={staticSection}> -->
                            <!-- <CardMedia 
                                style={{height:"310px", width: "223px"}}
                                // class={itemImage}
                                image={img}
                                /> -->
                        <!-- </div> -->
                        
                        <div class="flex-col flex-section">
                            <div class="scroll-section" style="overflow:auto">
                            <table size="small" >
                                <th>
                                    <tr>
                                        <td>Style</td>
                                        <td>Status</td>
                                    </tr>
                                </th>
                                <!-- <TableBody> -->
                                    
                                        <!-- inventoryCardIds.map(inventoryCardId => {
                                            const item = props.inventoryCardsById[inventoryCardId];
                                            return(
                                            <TableRow key={item.id}>
                                                <TableCell>
                                                    <Typography>{(item.isFoil && " foil") || "normal"}</Typography>
                                                </TableCell>
                                                <TableCell>
                                                    <Typography>
                                                        { item.statusId === 1 && "Inventory/Deck" }
                                                        { item.statusId === 2 && "Wish List" }
                                                        { item.statusId === 3 && "Sell List" }
                                                    </Typography>
                                                    {/* {item.deckCards.length > 0 && "In a Deck"}
                                                    {item.deckCards.length === 0 && item.statusId === 1 && "Inventory"}
                                                    { item.statusId === 2 && "Buy List"}
                                                    { item.statusId === 3 && "Sell List"} */}
                                                </TableCell>

                                                {/* <TableCell>
                                                    {item.deckCards.length === 0 && item.statusId === 1 && 
                                                        <Button size="small" variant="contained" onClick={() => props.handleUpdateCardClick && props.handleUpdateCardClick(item, 3)}>
                                                            To Sell List
                                                        </Button>
                                                    }
                                                    { item.statusId === 2 && 
                                                        <Button size="small" variant="contained" onClick={() => props.handleUpdateCardClick && props.handleUpdateCardClick(item, 1)}>
                                                            Mark as Arrived
                                                        </Button>
                                                    }
                                                    { item.statusId === 3 && 
                                                        <Button size="small" variant="contained" onClick={() => props.handleDeleteCardClick && props.handleDeleteCardClick(item.id)}>
                                                            Delte
                                                        </Button>
                                                    }
                                                </TableCell> */}
                                            </TableRow>
                                            )
                                        })
                                     -->
                                <!-- </TableBody> -->
                            </table>
                            </div>
                            
                        </div>
                    </div>
                <!-- </Card>  -->
            <!-- )
        })
    } -->
    </div>


</div>

<div mat-dialog-actions fxLayout="column" fxLayoutAlign="none end" fxLayoutGap="10px">
    <!-- <Button size="medium" onClick={() => this.handleCloseModalClick()}>Close</Button> -->
    <!-- <button mat-raised-button (click)="handleCloseModalClick()">Close</button> -->
    <!-- <button mat-raised-button (click)="onCancelClick()">Cancel</button> -->
</div>
