// Carpentry/ClientApp/src/features/inventory/inventory-overview/components/InventoryFilterBar.tsx
import React from 'react';
import CheckBoxOutlineBlankIcon from '@material-ui/icons/CheckBoxOutlineBlank'
import CheckBoxIcon from '@material-ui/icons/CheckBox'
import {Paper, Box, TextField, MenuItem, FormControl, FormControlLabel, Checkbox, Button} from '@material-ui/core';
// import { appStyles, combineStyles } from '../../../styles/appStyles';
import styles from '../../../../app/App.module.css';
import {NumericFilter} from "../../../../common/components/NumericFilter";
import {SelectFilter} from "../../../../common/components/SelectFilter";
import {TextFilter} from "../../../../common/components/TextFilter";
import {useAppSelector} from "../../../../hooks";

interface InventoryFilterBarProps{
  // searchFilter: InventoryFilterProps,
  // viewMethod: "grid" | "table";
  // filterOptions: AppFiltersDto,
  // handleFilterChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
  // handleBoolFilterChange: (filter: string, value: boolean) => void;
  // handleSearchButtonClick: () => void;
}

//This bar should just be a flex-grid of filter elements
//It probably shouldn't even have the "search" button
export const InventoryFilterBar = (props: InventoryFilterBarProps): JSX.Element => {
  // Need this to cache?
  // try this?
  // https://material-ui.com/components/autocomplete
  
  // TODO - Ensure these selectors aren't fucking up by trying to compare objects (maybe make them a fancy selector in the slice)
  const searchFilter = useAppSelector(state => state.inventory.overviews.filters);
  const filterOptions = useAppSelector(state => state.core.filterOptions);

  const handleFilterChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
    
  }
  const handleBoolFilterChange = (filter: string, value: boolean): void => {
    
  }
  
  const handleSearchButtonClick = (): void => {
  
  }
  
  return(
    <Paper className={[styles.outlineSection, styles.flexCol].join(' ')}>
      <Box className={[styles.flexSection, styles.flexRow].join(' ')}>

        <SelectFilter id="group-by-filter" name="groupBy" value={searchFilter.groupBy} selectMultiple={false}
                      options={filterOptions.groupBy} handleFilterChange={handleFilterChange} />

        <SelectFilter id="sort-by-filter" name="sortBy" value={searchFilter.sortBy} selectMultiple={false}
                      options={filterOptions.sortBy} handleFilterChange={handleFilterChange} />

        <BooleanCheckboxGroup handleBoolFilterChange={handleBoolFilterChange}
                              options={[{name: "Desc", value: "sortDescending", checked: searchFilter.sortDescending}]} />

        <SelectFilter id="set-filter" name="set" value={searchFilter.set} selectMultiple={false}
                      options={filterOptions.sets} handleFilterChange={handleFilterChange} />

        <SelectFilter id="type-filter" name="type" value={searchFilter.type} selectMultiple={false}
                      options={filterOptions.types} handleFilterChange={handleFilterChange} />

        <SelectFilter id="color-identity-filter" name="colorIdentity" selectMultiple={true} value={searchFilter.colorIdentity}
                      options={filterOptions.colors} handleFilterChange={handleFilterChange} />

        <BooleanCheckboxGroup handleBoolFilterChange={handleBoolFilterChange}
                              options={[{name: "Exclusive", value: "exclusiveColorFilters", checked: searchFilter.exclusiveColorFilters},
                                {name: "Multi", value: "multiColorOnly", checked: searchFilter.multiColorOnly}]} />

      </Box>
      <Box className={[styles.flexSection, styles.flexRow].join(' ')}>
        <Box className={[styles.flexSection, styles.flexRow].join(' ')}>

          <TextFilter name="text" value={searchFilter.text}
                      handleFilterChange={handleFilterChange} />

          <SelectFilter id="rarity-filter" name="rarity" value={searchFilter.rarity} selectMultiple={true}
                        options={filterOptions.rarities} handleFilterChange={handleFilterChange} />

          <NumericFilter id="min-count-filter" name="minCount" value={searchFilter.minCount}
                         handleFilterChange={handleFilterChange} />

          <NumericFilter id="max-count-filter" name="maxCount" value={searchFilter.maxCount}
                         handleFilterChange={handleFilterChange} />

          <NumericFilter id="skip-filter" name="skip" value={searchFilter.skip}
                         handleFilterChange={handleFilterChange} />

          <NumericFilter id="take-filter" name="take" value={searchFilter.take}
                         handleFilterChange={handleFilterChange} />

        </Box>
        <Box className={[styles.staticSection, styles.center, styles.sidePadded].join(' ')}>
          <Button variant="contained" size="medium" color="primary" onClick={() => handleSearchButtonClick()}>
            Search
          </Button>
        </Box>
      </Box>
    </Paper>
  );
}

interface BooleanCheckboxOption {
  name: string;
  value: string;
  checked: boolean;
}
interface BooleanCheckboxGroupProps {
  options: BooleanCheckboxOption[];
  handleBoolFilterChange: (filter: string, value: boolean) => void;
}
function BooleanCheckboxGroup(props: BooleanCheckboxGroupProps): JSX.Element {
  return(
    <FormControl component="fieldset">
      {
        props.options.map((item) => (<FormControlLabel
          key={item.value}
          name={item.value}
          onChange={(e, checked) => {props.handleBoolFilterChange(item.value,checked)}}
          checked={item.checked}
          control={<Checkbox  color="primary" icon={<CheckBoxOutlineBlankIcon fontSize="small" />} checkedIcon={<CheckBoxIcon fontSize="small" />} />}
          label={item.name} />))
      }
    </FormControl>
  );
}

// Carpentry.Angular/ClientApp/src/app/inventory/inventory-overview/inventory-filter-bar/inventory-filter-bar.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { AppFiltersDto } from "src/app/settings/models";
import { InventoryFilterProps } from "../../models";

@Component({
    selector: 'app-inventory-filter-bar',
    templateUrl: 'inventory-filter-bar.component.html',
    styleUrls: ['inventory-filter-bar.component.less'],
})
export class InventoryFilterBarComponent implements OnInit {
    @Input() searchFilter: InventoryFilterProps;
    @Input() viewMethod: "grid" | "table";
    @Input() filterOptions: AppFiltersDto;

    // @Output() onFilterChange = new EventEmitter<void>(); //: (event: React.ChangeEvent<HTMLInputElement>) => void;
    // @Output() onBoolFilterChange = new EventEmitter<{filter: string, value: boolean}>(); //: (filter: string, value: boolean) => void;
    @Output() onSearchButtonClick = new EventEmitter<void>(); //: () => void;

    constructor() {}

    ngOnInit(): void {
        // this.searchFilter = {
        //     groupBy: "print", // "name" | "print" | "unique", //InventoryGroupMethod,
        //     sortBy: "collectorNumber", //"name" | "price" | "cmc" | "count" | "collectorNumber", //InventorySortMethod,
        //     set: '',
        //     text: '',
        //     type: '',
        //     colorIdentity: [],
        //     exclusiveColorFilters: false,
        //     multiColorOnly: false,
        //     rarity: [],
        //     minCount: 0,
        //     maxCount: 0,
        //     skip: 0,
        //     take: 0,
        //     sortDescending: false,
        // }
    }

    searchButtonClick(): void {
        this.onSearchButtonClick.emit();
    }

    // filterChange(filter: string, value: boolean): void {

    // }
}
<mat-card fxLayout="column" class="outline-section">
    <div fxLayout="row" class="flex-section">

        <div class="flex-section side-padded">
            <mat-form-field class="stretch">
                <mat-label>Group by</mat-label>
                <mat-select [(ngModel)]="searchFilter.groupBy">
                    <mat-option *ngFor="let item of filterOptions?.groupBy" [value]="item.value">{{item.name}}</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <!-- <SelectFilter name="groupBy" value={props.searchFilter.groupBy} selectMultiple={false} 
            options={props.filterOptions.groupBy} handleFilterChange={props.handleFilterChange} /> -->

        <div class="flex-section side-padded">
            <mat-form-field class="stretch">
                <mat-label>Sort by</mat-label>
                <mat-select [(ngModel)]="searchFilter.sortBy">
                    <mat-option *ngFor="let item of filterOptions?.sortBy" [value]="item.value">{{item.name}}</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <!-- <SelectFilter name="sortBy" value={props.searchFilter.sortBy} selectMultiple={false}
            options={props.filterOptions.sortBy} handleFilterChange={props.handleFilterChange} /> -->



        <!-- <BooleanCheckboxGroup handleBoolFilterChange={props.handleBoolFilterChange}
            options={[{name: "Desc", value: "sortDescending", checked: props.searchFilter.sortDescending}]} /> -->


        <div class="flex-section side-padded">
            <mat-form-field class="stretch">
                <mat-label>Set</mat-label>
                <mat-select [(ngModel)]="searchFilter.set">
                    <mat-option *ngFor="let item of filterOptions?.sets" [value]="item.value">{{item.name}}</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <!-- <SelectFilter name="set" value={props.searchFilter.set} selectMultiple={false}
            options={props.filterOptions.sets} handleFilterChange={props.handleFilterChange} /> -->

        <div class="flex-section side-padded">
            <mat-form-field class="stretch">
                <mat-label>Type</mat-label>
                <mat-select [(ngModel)]="searchFilter.type">
                    <mat-option *ngFor="let item of filterOptions?.types" [value]="item.value">{{item.name}}</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <!-- <SelectFilter name="type" value={props.searchFilter.type} selectMultiple={false}
            options={props.filterOptions.types} handleFilterChange={props.handleFilterChange} /> -->

        <div class="flex-section side-padded">
            <mat-form-field class="stretch">
                <mat-label>Color Identity</mat-label>
                <mat-select [(ngModel)]="searchFilter.colorIdentity">
                    <mat-option *ngFor="let item of filterOptions?.colors" [value]="item.value">{{item.name}}</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <!-- <SelectFilter name="colorIdentity" selectMultiple={true} value={props.searchFilter.colorIdentity}
            options={props.filterOptions.colors} handleFilterChange={props.handleFilterChange} /> -->



        <!-- <BooleanCheckboxGroup handleBoolFilterChange={props.handleBoolFilterChange}
            options={[{name: "Exclusive", value: "exclusiveColorFilters", checked: props.searchFilter.exclusiveColorFilters},
            {name: "Multi", value: "multiColorOnly", checked: props.searchFilter.multiColorOnly}]} /> -->
        

    </div>

    <div fxLayout="row" class="flex-section">
        <div fxLayout="row" class="flex-section">

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Text</mat-label>
                    <!-- (change)="filterChange($event)"  style="text-transform: capitalize" -->
                    <input matInput [(ngModel)]="searchFilter.text" margin="normal" />
                </mat-form-field>
            </div>

            <!-- (onFilterChange)="handleFilterChange($event)" -->
            <!-- <app-text-filter [name]="'Text'" [(value)]="searchFilter.text"></app-text-filter> -->
            <!-- <TextFilter name="text" value={props.searchFilter.text}
            handleFilterChange={props.handleFilterChange} /> -->

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Rarity</mat-label>
                    <mat-select [(ngModel)]="searchFilter.rarity">
                        <mat-option *ngFor="let item of filterOptions?.rarities" [value]="item.value">{{item.name}}</mat-option>
                    </mat-select>
                </mat-form-field>
            </div>
            <!-- <SelectFilter name="rarity" value={props.searchFilter.rarity} selectMultiple={true}
                options={props.filterOptions.rarities} handleFilterChange={props.handleFilterChange} /> -->

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Min Count</mat-label>
                    <input matInput type="number" [(ngModel)]="searchFilter.minCount" />
                </mat-form-field>
            </div>
            <!-- <NumericFilter name="minCount" value={props.searchFilter.minCount}
                handleFilterChange={props.handleFilterChange} /> -->

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Max Count</mat-label>
                    <input matInput type="number" [(ngModel)]="searchFilter.maxCount" />
                </mat-form-field>
            </div>
            <!-- <NumericFilter name="maxCount" value={props.searchFilter.maxCount}
                handleFilterChange={props.handleFilterChange} /> -->

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Skip</mat-label>
                    <input matInput type="number" [(ngModel)]="searchFilter.skip" />
                </mat-form-field>
            </div>
            <!-- <NumericFilter name="skip" value={props.searchFilter.skip}
                handleFilterChange={props.handleFilterChange} /> -->

            <div class="flex-section side-padded">
                <mat-form-field class="stretch">
                    <mat-label>Take</mat-label>
                    <input matInput type="number" [(ngModel)]="searchFilter.take" />
                </mat-form-field>
            </div>
            <!-- <NumericFilter name="take" value={props.searchFilter.take}
                handleFilterChange={props.handleFilterChange} /> -->

        </div>
        <div className="static-section center side-padded">
            <button mat-button variant="contained" size="medium" color="primary" (click)="searchButtonClick()">
                Search
            </button>
        </div>
    </div>

</mat-card>
