// Carpentry.UI/ClientApp/src/containers/DeckEditor/DeckStatsBar.tsx
import React from 'react';

import { Typography, Box, Paper, TextField, TableRow, TableHead, Table, TableCell, Tab, TableBody } from '@material-ui/core';

interface ComponentProps{
    deckStats: DeckStats;
}

export default function DeckStatsBar(props: ComponentProps): JSX.Element {
    return (
        <Paper className="flex-row outline-section">
            <Box className="outline-section">
                <Typography variant="h6">Card Count</Typography>
                <Typography variant="h5">{props.deckStats.totalCount}</Typography>
                {/* <TextField 
                    disabled
                    label="Card Count"
                    defaultValue={props.deckStats.totalCount}
                /> */}
            </Box>

            <Box className="outline-section">
                <Table size="small">
                    <TableHead>
                        <TableRow>
                            {
                                Object.keys(props.deckStats.typeCounts).map((key) => <TableCell key={`stats-type-head-${key}`} size="small">{key}</TableCell>)
                            }
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        <TableRow>
                            {
                                Object.keys(props.deckStats.typeCounts).map((key) => <TableCell key={`stats-type-cell-${key}`} size="small">{props.deckStats.typeCounts[key]}</TableCell>)
                            }
                        </TableRow>
                    </TableBody>
                </Table>
                {/* {
                    Object.keys(props.deckStats.typeCounts).map((key) => {
                        return (
                            <TextField 
                                disabled
                                label={key}
                                defaultValue={props.deckStats.typeCounts[key]}
                            />
                        );
                    })
                } */}
            </Box>

            <Box className="outline-section">
                {/* <Typography>CMC Breakdown</Typography> */}
                <Table size="small">
                    <TableHead>
                        <TableRow>
                            {
                                Object.keys(props.deckStats.costCounts).map((key) => <TableCell key={`stats-cmc-head-${key}`} size="small">{key}</TableCell>)
                            }
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        <TableRow>
                            {
                                Object.keys(props.deckStats.costCounts).map((key) => <TableCell key={`stats-cmc-cell-${key}`} size="small">{props.deckStats.costCounts[key]}</TableCell>)
                            }
                        </TableRow>
                    </TableBody>
                </Table>
                {/* {
                    

                    Object.keys(props.deckStats.costCounts).map((key) => {
                        return (
                            <TextField 
                                disabled
                                label={key}
                                defaultValue={props.deckStats.costCounts[key]}
                            />
                        );
                    })
                } */}
            </Box>

            <Box className="outline-section flex-col">
                <Typography variant="h6">Total Cost</Typography>
                <Typography variant="h5">{props.deckStats.totalCost}</Typography>
                {/* <TextField 
                    disabled
                    label="Total Cost"
                    defaultValue={props.deckStats.totalCost}
                /> */}
            </Box>
        </Paper>
    );
}

// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-stats-bar/deck-stats-bar.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { DeckStats } from "../../models";

@Component({
    selector: 'app-deck-stats-bar',
    templateUrl: 'deck-stats-bar.component.html',
    styleUrls: ['deck-stats-bar.component.less']
})
export class DeckStatsBarComponent implements OnInit {
    @Input() deckStats: DeckStats;
    constructor() { }
    ngOnInit(): void { }
}
<div fxLayout="row" fxLayoutAlign=" none" class="outline-section" *ngIf="deckStats">
    <div class="outline-section">
        <h6>Card Count</h6>
        <h5>{{deckStats.totalCount}}</h5>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.typeCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.typeCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.costCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.costCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.tagCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.tagCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <h6>Total Cost</h6>
        <h5>{{deckStats.totalCost}}</h5>
    </div>
</div>
