// Carpentry/ClientApp/src/decks/deck-editor/components/DeckStatsBar.tsx
import React from 'react';

import { Typography, Box, Paper, TableRow, TableHead, Table, TableCell, TableBody } from '@material-ui/core';
import { combineStyles, appStyles } from '../../../styles/appStyles';

interface ComponentProps{
    deckStats: DeckStats;
}

export default function DeckStatsBar(props: ComponentProps): JSX.Element {
  const { outlineSection, flexCol, flexRow, } = appStyles();
  
  return (
    <Paper className={combineStyles(flexRow, outlineSection)}>
      <Box className={outlineSection}>
        <Typography variant="h6">Card Count</Typography>
        <Typography variant="h5" id="deck-stats-count">{props.deckStats.totalCount}</Typography>
      </Box>

      <Box className={outlineSection}>
        <Table size="small">
          <TableHead>
            <TableRow>
              {
                Object.keys(props.deckStats.typeCounts).map((key) => 
                  <TableCell key={`stats-type-head-${key}`} className="stats-type-head" size="small">{key}</TableCell>
                )
              }
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              {
                Object.keys(props.deckStats.typeCounts).map((key) => 
                  <TableCell key={`stats-type-cell-${key}`} className="stats-type-cell" size="small">{props.deckStats.typeCounts[key]}</TableCell>
                )
              }
            </TableRow>
          </TableBody>
        </Table>
      </Box>

      <Box className={outlineSection}>
        <Table size="small">
          <TableHead>
            <TableRow>
              {
                Object.keys(props.deckStats.costCounts).map((key) => 
                  <TableCell key={`stats-cmc-head-${key}`} className="stats-cmc-head" size="small">{key}</TableCell>
                )
              }
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              {
                Object.keys(props.deckStats.costCounts).map((key) => 
                  <TableCell key={`stats-cmc-cell-${key}`} className="stats-cmc-cell" size="small">{props.deckStats.costCounts[key]}</TableCell>
                )
              }
            </TableRow>
          </TableBody>
        </Table>
      </Box>

      <Box className={outlineSection}>
        <Table size="small">
          <TableHead>
            <TableRow>
              {
                Object.keys(props.deckStats.tagCounts).map((key) => <TableCell key={`stats-type-head-${key}`} size="small">{key}</TableCell>)
              }
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              {
                Object.keys(props.deckStats.tagCounts).map((key) => <TableCell key={`stats-type-cell-${key}`} size="small">{props.deckStats.tagCounts[key]}</TableCell>)
              }
            </TableRow>
          </TableBody>
        </Table>
      </Box>
      <Box className={combineStyles(outlineSection, flexCol)}>
        <Typography variant="h6">Total Cost</Typography>
        <Typography variant="h5">{props.deckStats.totalCost}</Typography>
      </Box>
    </Paper>
  );
}

// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-stats-bar/deck-stats-bar.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { DeckStats } from "../../models";

@Component({
    selector: 'app-deck-stats-bar',
    templateUrl: 'deck-stats-bar.component.html',
    styleUrls: ['deck-stats-bar.component.less']
})
export class DeckStatsBarComponent implements OnInit {
    @Input() deckStats: DeckStats;
    constructor() { }
    ngOnInit(): void { }
}
<div fxLayout="row" fxLayoutAlign=" none" class="outline-section" *ngIf="deckStats">
    <div class="outline-section">
        <h6>Card Count</h6>
        <h5>{{deckStats.totalCount}}</h5>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.typeCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.typeCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.costCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.costCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <table size="small">
            <tr>
                <th *ngFor="let item of deckStats.tagCounts | keyvalue">{{item.key}}</th>
            </tr>
            <tr>
                <td *ngFor="let item of deckStats.tagCounts | keyvalue">{{item.value}}</td>
            </tr>
        </table>
    </div>

    <div class="outline-section">
        <h6>Total Cost</h6>
        <h5>{{deckStats.totalCost}}</h5>
    </div>
</div>
