// Carpentry/ClientApp/src/components/DeckCardList.tsx
//table of deck cards
import React from 'react';

import {  Paper, Table, TableHead, TableRow, TableCell, TableBody } from '@material-ui/core';

interface ComponentProps{
    //totalPrice: number;
    // deckProperties: DeckProperties;
    // onEditClick: () => void;
    cardOverviews: DeckCardOverview[];
    onCardSelected: (card: DeckCardOverview) => void;
}

export default function DeckCardList(props: ComponentProps): JSX.Element {
    // className="flex-section"
    return (
        <Paper>
            <Table size="small">
                <TableHead>
                    <TableRow>
                        <TableCell>Name</TableCell>
                        <TableCell>Count</TableCell>
                        <TableCell>Type</TableCell>
                        <TableCell>Cost</TableCell>
                        <TableCell>Category</TableCell>
                    </TableRow>
                </TableHead>
                <TableBody>
                    {
                        props.cardOverviews.map(cardItem => 
                            <TableRow onClick={() => props.onCardSelected(cardItem)} onMouseEnter={() => props.onCardSelected(cardItem)}
                                key={cardItem.id+cardItem.name}>
                                <TableCell>{cardItem.name}</TableCell>
                                <TableCell>{cardItem.count}</TableCell>
                                <TableCell>{cardItem.type}</TableCell>
                                <TableCell>{cardItem.cost}</TableCell>
                                <TableCell>{cardItem.category}</TableCell>
                            </TableRow>
                        )
                    }
                </TableBody>
            </Table>
        </Paper>
    );
}

// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-card-list/deck-card-list.component.ts
import { Component, Input, OnInit, Output, EventEmitter } from "@angular/core";
import { DeckCardOverview } from "../../models";

@Component({
    selector: 'app-deck-card-list',
    templateUrl: 'deck-card-list.component.html',
    styleUrls: ['deck-card-list.component.less']
})
export class DeckCardListComponent implements OnInit {
    @Input() cardOverviews: DeckCardOverview[];
    @Output() onCardSelected = new EventEmitter<DeckCardOverview>();

    constructor() { }
    ngOnInit(): void { }    

    cardSelected(card: DeckCardOverview): void {
        this.onCardSelected.emit(card);
    }
}
<div>
    <!-- TODO Replace with angular table -->
    <table size="small">
        <tr>
            <th>Name</th>
            <th>Count</th>
            <th>Type</th>
            <th>Cost</th>
            <th>Category</th>
        </tr>
        <tr *ngFor="let cardItem of cardOverviews" (click)="cardSelected(cardItem)" (mouseenter)="cardSelected(cardItem)">
            <td>{{cardItem.name}}</td>
            <td>{{cardItem.count}}</td>
            <td>{{cardItem.type}}</td>
            <td>{{cardItem.cost}}</td>
            <td>{{cardItem.category}}</td>
        </tr>
    </table>
</div>
