// Carpentry.Angular/ClientApp/src/app/decks/deck-editor/deck-card-detail/deck-card-detail.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { DeckCardDetail, DeckCardOverview } from "../../models";

@Component({
    selector: 'app-deck-card-detail',
    templateUrl: 'deck-card-detail.component.html',
    styleUrls: ['deck-card-detail.component.less']
    
})
export class DeckCardDetailComponent implements OnInit {
    @Input() selectedCard: DeckCardOverview | null;
    @Input() inventoryCards: DeckCardDetail[];

    @Output() onMenuClick = new EventEmitter<void>();
    // (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;

    @Output() onMenuClose = new EventEmitter<void>();
    @Output() onCardDetailClick = new EventEmitter<number>();
    @Output() onCardTagsClick = new EventEmitter<number>();

    
    constructor() {}

    ngOnInit(): void {}

    menuClick(): void {
        this.onMenuClick.emit();
    }

    menuClose(): void {
        this.onMenuClose.emit();
    }

    cardDetailClick(): void {
        this.onCardDetailClick.emit();
    }

    cardTagsClick(): void {
        this.onCardTagsClick.emit();
    }
}
<!-- (props.selectedCard === null) -->
<div className="staticSection">
    <mat-card>
        <mat-card-header>
            <!-- TODO - figure out to how to render as a body1 instead of [whatever the title is] -->
            <mat-card-title>
                <p>no card selected</p>
            </mat-card-title>
        </mat-card-header>
        <mat-card-content>
            <p>select a card</p>
        </mat-card-content>
    </mat-card>
</div>

<!-- else -->
<div className="staticSection">
                
    <mat-card>
        <img *ngIf="selectedCard" style="height:310px; width: 223px" src="selectedCard.img" />

        <mat-card-content>
            <table size="small">
                <tr>
                    <th>Card Detail</th>
                    <th></th>
                </tr>
            
                <tr *ngFor="let item of inventoryCards">

                    <td *ngIf="item.inventoryCardId" style="text-transform:uppercase">
                        {{item.set}} - {{item.collectorNumber}}{{item.isFoil && "(foil)"}}
                    </td>
                    <td *ngIf="!item.inventoryCardId">
                        Empty
                    </td>
                    
                    <td size="small">
                        <a mat-icon-button (click)="menuClick()">more_vert</a>
                        <!-- <IconButton size="small" onClick={props.onMenuClick} name={item.name} value="item.id">
                            <MoreVert />
                        </IconButton> -->
                    </td>
                </tr>
            </table>
        </mat-card-content>
        <mat-card-actions>
            <button mat-button (click)="selectedCard && cardDetailClick(selectedCard.cardId)"
                color="primary" variant="contained">Details</button>
            <button mat-button (click)="selectedCard && cardTagsClick(selectedCard.cardId)"
                color="primary" variant="contained">Tags</button>
        </mat-card-actions>
    </mat-card>
</div>

// Carpentry/ClientApp/src/features/decks/deck-editor/components/DeckCardDetail.tsx
import {  Table, TableHead, TableRow, TableCell, TableBody, Box, CardActions, Button, Card, CardHeader, CardMedia, CardContent, Typography, IconButton } from '@material-ui/core';
import React, {useState} from 'react';
import { MoreVert } from '@material-ui/icons';
import styles from '../../../../app/App.module.css'
import {useAppDispatch, useAppSelector} from "../../../../app/hooks";
import {cardMenuButtonClicked, getSelectedDeckDetails} from "../deckEditorSlice";
import {useHistory} from "react-router";
import CardMenu from "./CardMenu";

interface ComponentProps{
    deckId: number;
}

export default function DeckCardDetail(props: ComponentProps): JSX.Element {
    //TODO - make slice selector
    const selectedCard: DeckCardOverview | null = useAppSelector(state => {
        const selectedOverviewCardId = state.decks.deckEditor.selectedOverviewCardId;
        if(selectedOverviewCardId){
            return state.decks.detail.cardOverviews.byId[selectedOverviewCardId];
        }
        return null; 
    });
    
    const inventoryCards = useAppSelector(getSelectedDeckDetails);
    
    const dispatch = useAppDispatch();
    const history =  useHistory();

    const [menuAnchor, setMenuAnchor] = useState<HTMLButtonElement | null>(null);
    
    
    const onMenuClick = (event: React.MouseEvent<HTMLButtonElement, MouseEvent>): void => {
        // dispatch(cardMenuButtonClicked(event.currentTarget));
        setMenuAnchor(event.currentTarget);
    }
    
    // console.log('hmm', menuAnchor)
    
    const onMenuClose = (): void => {
        console.log('menu anchor set')
        setMenuAnchor(null)
    }
    
    const onCardDetailClick = (cardId: number): void => {
        history.push(`/decks/${props.deckId}?cardId=${cardId}&show=detail`);
    }
    
    const onCardTagsClick = (cardId: number): void => {
        history.push(`/decks/${props.deckId}?cardId=${cardId}&show=tags`);
    }
    
    if(selectedCard === null){
        return (
            <Box className={styles.staticSection}>
                <Card>
                    <CardHeader titleTypographyProps={{variant:"body1"}} title={"no card selected"}/>
                    <CardContent>
                        <Typography>select a card</Typography>
                    </CardContent>
                </Card>
            </Box>
        );
    }
    else {
        return (
            <React.Fragment>
                <CardMenu 
                  cardMenuAnchor={menuAnchor}
                  cardCategoryId={selectedCard?.category || ''}
                  onCardMenuClose={onMenuClose}
                />
                <Box className={styles.staticSection}>
                    <Card>
                        {
                            <CardMedia style={{height:"310px", width: "223px"}} image={selectedCard.img} />
                        }
                        <CardContent>
                            <Table size="small">
                                <TableHead>
                                    <TableRow>
                                        <TableCell colSpan={2}>Card Detail</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {
                                        inventoryCards.map(item => {

                                            const rowDeckCardId = item.id;
                                            return(
                                              <TableRow key={item.id}>
                                                  {
                                                      item.inventoryCardId &&
                                                      <TableCell style={{textTransform:"uppercase"}}>
                                                          {`${item.set} - ${item.collectorNumber}`}{item.isFoil &&" (foil)"}
                                                      </TableCell>
                                                  }
                                                  {
                                                      !item.inventoryCardId &&
                                                      <TableCell>
                                                          Empty
                                                      </TableCell>
                                                  }
                                                  <TableCell size="small">
                                                      <IconButton size="small" onClick={onMenuClick} name={item.name} value={rowDeckCardId}>
                                                          <MoreVert />
                                                      </IconButton>
                                                  </TableCell>
                                              </TableRow>
                                            )
                                        })
                                    }
                                </TableBody>
                            </Table>
                        </CardContent>
                        <CardActions>
                            <Button
                              onClick={() => selectedCard && onCardDetailClick(selectedCard.cardId)}
                              color="primary"
                              variant="contained">Details</Button>
                            <Button
                              onClick={() => selectedCard && onCardTagsClick(selectedCard.cardId)}
                              color="primary"
                              variant="contained">Tags</Button>
                        </CardActions>
                    </Card>
                </Box>
            </React.Fragment>
        );
    }
}
