// Carpentry.React/ClientApp/src/features/settings/tracked-sets/TrackedSets.tsx
﻿import React, {useEffect} from 'react';
import {
  Box,
  Button,
  FormControlLabel,
  IconButton,
  Paper,
  Switch,
  Table, TableBody, TableCell,
  TableHead, TableRow,
  Typography
} from "@material-ui/core";
import {Add, Delete, Refresh} from "@material-ui/icons";
import {AppLayout} from "../../../common/components/AppLayout";
import styles from "../../../app/App.module.css";
import {SetDetailDto} from "../../../../../../Carpentry.Angular/ClientApp/src/app/settings/models";
import {useAppSelector} from "../../../app/hooks";


const TrackedSetsRow = (props: { setDetail: SetDetailDto}): JSX.Element => {
  const setDetail = props.setDetail; // lazy

  const onAddSetClick = (setId: number): void => {

  }
  const onRemoveSetClick = (setId: number): void => {

  }
  const onUpdateSetClick = (setId: number): void => {

  }
  
  return (
    <TableRow key={setDetail.code} className="set-row">
      <TableCell>{setDetail.code}</TableCell>
      <TableCell>{setDetail.name}</TableCell>
      <TableCell>{setDetail.inventoryCount}</TableCell>
      <TableCell>{setDetail.isTracked && `${setDetail.collectedCount}/${setDetail.totalCount}`}</TableCell>
      <TableCell>{setDetail.dataLastUpdated}</TableCell>
      <TableCell>
        { !setDetail.isTracked &&
        <IconButton className="add-button" color="inherit" onClick={() => {onAddSetClick(setDetail.setId)}}>
            <Add />
        </IconButton>
        }
        { setDetail.isTracked &&
        <React.Fragment>
            <IconButton color="inherit" onClick={() => {onUpdateSetClick(setDetail.setId)}}>
                <Refresh />
            </IconButton>
            <IconButton color="inherit" onClick={() => {onRemoveSetClick(setDetail.setId)}}>
                <Delete />
            </IconButton>
        </React.Fragment>
        }
      </TableCell>
    </TableRow>
  );
}

export const TrackedSets = (): JSX.Element => {
  
  const trackedSetDetails: SetDetailDto[] = [];
  const showUntrackedValue = false;
  const isLoading = false;// useAppSelector(state => state.se)
  
  
  // useEffect - ensure loaded
  
  useEffect(() => {
    //ensure tracked sets are loaded
    //     this.props.dispatch(requestTrackedSets(this.props.showUntracked, false));
  })
  

  const onRefreshClick = (): void => {

  }
  
  const onShowUntrackedClick = (): void => {
    
  }

  return(
    <AppLayout title="Settings - Tracked Sets" isLoading={isLoading}>
      <Box>
        <Box className={styles.flexRow}>
          <Box className={styles.flexSection}>
            <Typography variant="h4">
              Tracked Sets
            </Typography>
          </Box>
          <FormControlLabel id='show-untracked-toggle'
                            onClick={onShowUntrackedClick}
                            control={
                              <Switch
                                checked={showUntrackedValue}
                                name="checkedB"
                                color="primary" />
                            }
                            label="Show Untracked"
          />
          <Button disabled={true} color="primary" variant="contained" >Update All</Button>
          <IconButton color="inherit" onClick={onRefreshClick} id="refresh-button" >
            <Refresh />
          </IconButton>
        </Box>
        <Paper>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Code</TableCell>
                <TableCell>Name</TableCell>
                <TableCell>Owned</TableCell>
                <TableCell>Collected</TableCell>
                <TableCell>Last Updated</TableCell>
                <TableCell>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {/* TODO - pass in an ID instead of a whole object*/}
              { trackedSetDetails.map(setDetail =>
                <TrackedSetsRow setDetail={setDetail} />
              )}
            </TableBody>
          </Table>
        </Paper>
      </Box>
    </AppLayout>
  );
}

// Carpentry.Angular/ClientApp/src/app/settings/tracked-sets/tracked-sets.component.ts
import { Component, OnInit } from "@angular/core";
import { MatSlideToggleChange } from "@angular/material/slide-toggle";
import { CoreService } from "../core.service";
import { SetDetailDto } from "../models";

//TODO - title/buttons should be all on the same line
@Component({
    selector: 'app-tracked-sets',
    templateUrl: 'tracked-sets.component.html',
    styleUrls: ['tracked-sets.component.less']
})
export class TrackedSetsComponent implements OnInit {
    // setsById: { [id: number]: SetDetailDto };
    // setIds: number[];
    // isLoading: boolean;
    
    displayedColumns: string[] = ['code','name','owned','collected','lastUpdated','actions'];
    setDetails: SetDetailDto[];
    // isLoading: boolean;
    public showUntracked: boolean; // = false;
    
    constructor(private coreService: CoreService) {}
    ngOnInit(): void {
        this.loadTrackedSets();
        this.showUntracked = false;

    }

    loadTrackedSets(update: boolean = false): void {
        this.setDetails = [];
        this.coreService.getTrackedSets(this.showUntracked, update).subscribe(result => {
            this.setDetails = result;
        }, err => console.log(`loadTrackedSets error: ${err}`));
    }

    showUntrackedToggleChange(event: MatSlideToggleChange) {
        this.showUntracked = event.checked;
        this.loadTrackedSets(false);
    }

    addTrackedSetClick(setId: number): void {
        this.coreService.addTrackedSet(setId).subscribe(() => {
            this.loadTrackedSets(false);
        }, err => console.log(err));
    }

    updateTrackedSetClick(setId: number): void {
        this.coreService.updateTrackedSet(setId).subscribe(() => {
            this.loadTrackedSets(false);
        }, err => console.log(err));
    }

    removeTrackedSetClick(setId: number): void {
        this.coreService.removeTrackedSet(setId).subscribe(() => {
            this.loadTrackedSets(false);
        }, err => console.log(err));
    }

}
<div>
    <mat-card>
        <div fxLayout="row">
            <div fxFill>
                <h4>Tracked Sets</h4>
            </div>

            <mat-slide-toggle [checked]="showUntracked" (change)="showUntrackedToggleChange($event)" color="primary" >Show Untracked</mat-slide-toggle>

            <button mat-button disabled color="primary" variant="contained" >Update All</button>

            <a mat-icon-button (click)="loadTrackedSets(true)">
                <mat-icon>refresh</mat-icon>
            </a>
        </div>

        <table mat-table [dataSource]="setDetails" class="mat-elevation-z8">

            <ng-container matColumnDef="code">
                <th mat-header-cell *matHeaderCellDef>
                    Code
                </th>
                <td mat-cell *matCellDef="let setDetail">
                    {{setDetail.code}}
                </td>
            </ng-container>

            <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef>
                    Name
                </th>
                <td mat-cell *matCellDef="let setDetail">
                    {{setDetail.name}}
                </td>
            </ng-container>

            <ng-container matColumnDef="owned">
                <th mat-header-cell *matHeaderCellDef>
                    Owned
                </th>
                <td mat-cell *matCellDef="let setDetail">
                    {{setDetail.inventoryCount}}
                </td>
            </ng-container>
            
            <ng-container matColumnDef="collected">
                <th mat-header-cell *matHeaderCellDef>
                    Collected
                </th>
                <td mat-cell *matCellDef="let setDetail">
                    {{setDetail.collectedCount}}/{{setDetail.totalCount}}
                </td>
            </ng-container>

            <ng-container matColumnDef="lastUpdated">
                <th mat-header-cell *matHeaderCellDef>
                    Last Updated
                </th>
                <td mat-cell *matCellDef="let setDetail">
                    {{setDetail.dataLastUpdated}}
                </td>
            </ng-container>
            
            <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>
                    Actions
                </th>
                <!-- TODO - get these icons to render on the same line, instead of stacked -->
                <td mat-cell *matCellDef="let setDetail">
                    <a mat-icon-button *ngIf="!setDetail.isTracked" (click)="addTrackedSetClick(setDetail.setId)">
                        <mat-icon>add</mat-icon>
                    </a>

                    <a mat-icon-button *ngIf="setDetail.isTracked" (click)="updateTrackedSetClick(setDetail.setId)">
                        <mat-icon>refresh</mat-icon>
                    </a>

                    <a mat-icon-button *ngIf="setDetail.isTracked" (click)="removeTrackedSetClick(setDetail.setId)">
                        <mat-icon>delete</mat-icon>
                    </a>
                </td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
            <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
        </table>
    </mat-card>
</div>
